# Generated by Django 3.2.14 on 2022-07-31 07:17

from django.db import migrations, models
import resume_website.storage


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(storage=resume_website.storage.PublicMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=resume_website.storage.PublicMediaStorage(), upload_to=''),
        ),
    ]
