# Generated by Django 3.2.14 on 2022-07-31 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20220731_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitWebRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('host', models.CharField(max_length=1000)),
                ('user_agent', models.CharField(blank=True, max_length=1000, null=True)),
                ('path', models.CharField(blank=True, max_length=1000, null=True)),
                ('remote_address', models.GenericIPAddressField()),
                ('remote_address_fwd', models.GenericIPAddressField(blank=True, null=True)),
                ('is_secure', models.BooleanField()),
                ('is_ajax', models.BooleanField()),
                ('meta', models.JSONField()),
                ('cookies', models.JSONField()),
                ('location', models.CharField(blank=True, max_length=1000, null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'visits',
                'db_table': 'resume_visit',
                'ordering': ['created_date', 'host', 'remote_address'],
            },
        ),
    ]
