# Generated by Django 3.2.14 on 2022-08-01 03:30

from django.db import migrations, models
import resume_website.storage


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='csv_path',
        ),
        migrations.AddField(
            model_name='profile',
            name='csv',
            field=models.FileField(blank=True, null=True, storage=resume_website.storage.PublicMediaStorage(), upload_to=''),
        ),
    ]
